services:

  backend:
    image: "jbc/purchasing-system/backend:0.1"
    build:
      context: ./backend
    ports:
      - "8000:8000"
    command: npm run dev

  frontend:
    image: "jbc/purchasing-system/frontend:0.1"
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm run start