export const apiAuthHello = "/api/auth/hello";
export const apiRegister = "/api/auth/register";
export const apiLogin = "/api/auth/login";
export const apiLogout = "api/auth/logout";
export const apiChangePassword = "/api/auth/change-pwd";
export const apiProtected = "/api/auth/protected";
export const apiUserHello = "/api/user/hello";
export const apiMe = "/api/user/me";
export const apiViewUser = (params: string) => `api/user/${params}`;
export const apiUpdateUser = "/api/user/update";
