export const apiAuthHello = "/api/auth/hello";
export const apiRegister = "/api/auth/register";
export const apiLogin = "/api/auth/login";
export const apiLogout = "api/auth/logout";
export const apiChangePassword = "/api/auth/change-pwd";
export const apiProtected = "/api/auth/protected";
export const apiUserHello = "/api/user/hello";
export const apiUserID = (params: string) => `/api/user/${params}`;
export const apiSupplierHello = "/api/supplier/hello";
export const apiSupplierID = (params: string) => `/api/supplier/${params}`;
export const apiSupplierMain = "/api/supplier";
export const apiSupplierSearch = "/api/supplier/search";
export const apiSupplierAll = "/api/supplier/all";
